# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  sister-ubuntu-service:
    hostname: sister-ubuntu
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    environment:
      GUEST_IP: ${GUEST_IP:-192.168.2.31}
      SSH_IP: ${SSH_IP:-192.168.2.2}
    networks:
      sister-ubuntu-network:
        ipv4_address: ${GUEST_IP:-192.168.2.31}
  sister-ssh-service:
    image: ubuntu
    stdin_open: true
    tty: true
    environment:
      SSH_IP: ${SSH_IP:-192.168.2.2}
    networks:
      sister-ubuntu-network:
        ipv4_address: ${SSH_IP:-192.168.2.2}

networks:
  sister-ubuntu-network:
    ipam:
      config:
        - subnet: ${SUBNET:-192.168.2.0/25}
