# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  sister-ubuntu-service:
    hostname: sister-ubuntu
    build: .
    stdin_open: true
    tty: true
