# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  sister-ubuntu-service:
    hostname: sister-ubuntu
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    environment:
      HOST_IP: ${HOST_IP:-192.168.2.1}
      GUEST_IP: ${GUEST_IP:-192.168.2.31}
    networks:
      sister-ubuntu-network:
        ipv4_address: ${GUEST_IP:-192.168.2.31}

networks:
  sister-ubuntu-network:
    ipam:
      config:
        - subnet: ${SUBNET:-192.168.2.0/25}
