# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  sister-ubuntu-service:
    hostname: sister-ubuntu
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    networks:
      sister-ubuntu-network:
        ipv4_address: 172.20.0.2

networks:
  sister-ubuntu-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
